name: Node + React CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: âœ… Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ§  Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # -------- BACKEND -----------
      - name: ğŸ“¦ Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      # -------- FRONTEND -----------
      - name: ğŸ“¦ Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install --force

      - name: ğŸ—ï¸ Build Frontend for Production
        working-directory: ./frontend
        run: npm run build
